###
# registerUser
POST http://localhost:4000/v1/auth/register
Content-Type: application/json

{
    "username":"mercy",
    "email":"mercy@gmail.com",
    "password":"Qwerty12!"
}

###
# loginUser
POST http://localhost:4000/v1/auth/login
Content-Type: application/json

{
    "username":"mercy",
    "password":"Qwerty12!"
}

###
# getUser
GET http://localhost:4000/v1/auth/get-user?id=18

###
#getUsers
GET http://localhost:4000/v1/auth/get-users?id=1

###
# UpdateUser
PATCH http://localhost:4000/auth/update/5/
Content-Type: application/json

{
    "username":"mkuru",
    "email":"mkuru@gmail.com",
    "password":"Qwerty12!"
}

###################
# DeleteUser
PATCH http://localhost:4000/auth/delete/4

