###
# getUser
GET http://localhost:4000/v1/users/get-user
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiYXJ0aHVyIiwiZW1haWwiOiJhcnRodXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU1NTA5MDg5LCJleHAiOjE3NTYxMTM4ODl9.nc92UTQBAjcCInQ0DXTrw86TwLO510rWo585WqGCr6I

###
#getUsers
GET http://localhost:4000/v1/users/get-users?page=1&&limit=10
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiYXJ0aHVyIiwiZW1haWwiOiJhcnRodXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU1NTA5MDg5LCJleHAiOjE3NTYxMTM4ODl9.nc92UTQBAjcCInQ0DXTrw86TwLO510rWo585WqGCr6I

###
# updateUser
PATCH http://localhost:4000/v1/users/update
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiYXJ0aHVyIiwiZW1haWwiOiJhcnRodXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU1NTA5MDg5LCJleHAiOjE3NTYxMTM4ODl9.nc92UTQBAjcCInQ0DXTrw86TwLO510rWo585WqGCr6I

{
    "username":"michael",
    "email":"michael@gmail.com",
    "password":"@Lance25"
}
