###
# getUser
GET http://localhost:4000/v1/users/get-user
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlMWQ1NjIyLTliNzktNDExMC1iNzhiLTk2YTI4NzU4NGI1MSIsInVzZXJuYW1lIjoiYXJ0aHVyIiwiZW1haWwiOiJhcnRodXJAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzU3OTUwNzM1LCJleHAiOjE3NTg1NTU1MzV9.D6x3eVih33U3Sz72Yf3-imfviSkftea3sWD9qNFzE24

###
#getUsers
GET http://localhost:4000/v1/users/get-users?page=1&&limit=10
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlMWQ1NjIyLTliNzktNDExMC1iNzhiLTk2YTI4NzU4NGI1MSIsInVzZXJuYW1lIjoiYXJ0aHVyIiwiZW1haWwiOiJhcnRodXJAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzU3OTUwNzM1LCJleHAiOjE3NTg1NTU1MzV9.D6x3eVih33U3Sz72Yf3-imfviSkftea3sWD9qNFzE24

###
# updateUser
PATCH http://localhost:4000/v1/users/update
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlMWQ1NjIyLTliNzktNDExMC1iNzhiLTk2YTI4NzU4NGI1MSIsInVzZXJuYW1lIjoiYXJ0aHVyIiwiZW1haWwiOiJhcnRodXJAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzU3OTUwNzM1LCJleHAiOjE3NTg1NTU1MzV9.D6x3eVih33U3Sz72Yf3-imfviSkftea3sWD9qNFzE24

{
    "username":"mikael",
    "email":"mikael@gmail.com",
    "password":"@Lance25"
}

###
# deleteUser
PATCH http://localhost:4000/v1/users/delete
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlMWQ1NjIyLTliNzktNDExMC1iNzhiLTk2YTI4NzU4NGI1MSIsInVzZXJuYW1lIjoiYXJ0aHVyIiwiZW1haWwiOiJhcnRodXJAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzU3OTUwNzM1LCJleHAiOjE3NTg1NTU1MzV9.D6x3eVih33U3Sz72Yf3-imfviSkftea3sWD9qNFzE24

